name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:

jobs:
  update:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: ubiquity-os/action-deploy-plugin@main
        with:
          pluginEntry: "${{ github.workspace }}/src/workflow-entry.ts"
          schemaPath: "${{ github.workspace }}/src/types/plugin-inputs.ts"
          treatAsEsm: true
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
